import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, K2D, Poppins, Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "../../lib/fontawesome";
import { i18n, type Locale } from "../../i18n-config";

config.autoAddCss = false;

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

const k2d = K2D({
  variable: "--font-k2d",
  subsets: ["latin"],
  weight: "600",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["500"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400"],
});

const roboto = Roboto({
  variable: "--font-robot",
  subsets: ["greek"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
    params: Promise<{ lang: Locale }>;
  }>,
) {
  const params = await props.params;
  return (
    <html lang={params.lang} suppressHydrationWarning>
      <body
        className={`bg-[#f7f9fc] ${geistSans.variable} ${geistMono.variable} ${k2d.variable} ${inter.variable} ${poppins.variable} ${montserrat.variable} ${roboto.variable}`}
      >
        {props.children}
      </body>
    </html>
  );
}
